#!/bin/sh -e

REGISTRY='https://registry-1.docker.io'

CACHE_DIR="$HOME/.cache/d-utils/"
mkdir -p "$CACHE_DIR"

if [ $# -lt 1 ] || [ "$1" = '-h' ]; then
	echo "usage: d-pull [-h] name[@tag] [dir]"
	exit 1
fi

if echo "$1" | grep -q '/'; then
	lib=$(echo "$1" | cut -d/ -f1)
	img=$(echo "$1" | cut -d/ -f2)
else
	lib='library'
	img="$1"
fi
if echo "$img" | grep -q '@'; then
	tag=$(echo "$img" | cut -d@ -f2)
	img=$(echo "$img" | cut -d@ -f1)
else
	tag='latest'
fi

if [ $# -gt 1 ]; then
	dir=$(realpath -m "$2")
else
	dir=$(realpath -m "$img")
fi
if [ -e "$dir" ]; then
	echo "$dir already exists"
	exit 1
fi

echo "pulling $lib/$img@$tag to $dir"
url="$REGISTRY/v2/$lib/$img"

echo "  fetching token"
auth_url=$(curl -s -I "$REGISTRY/v2/" | grep -i www-authenticate | sed 's/.*realm="\(.*\)",service="\(.*\)".*/\1?service=\2/')
auth_token=$(curl -s "$auth_url&scope=repository:$lib/$img:pull" | jq -r '.token')
auth="Authorization: Bearer $auth_token"

# fail if server reports error
curl --head -f --no-progress-meter -o /dev/null -H "$auth" "$url/manifests/$tag"

mkdir -p "$dir/rootfs"
echo "$lib/$img@$tag" > "$dir/image.txt"

echo "  fetching manifest"
curl -s -H "$auth" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" "$url/manifests/$tag" -o "$dir/manifest.json"

echo "  fetching config"
config=$(jq -r '.config.digest' "$dir/manifest.json")
curl -s -L -H "$auth" "$url/blobs/$config" | jq '.config' > "$dir/config.json"

echo "  fetching layers"
jq -r '.layers|map(.digest)|.[]' "$dir/manifest.json" | while read -r blob; do
	echo "     $blob"
	if [ -e "$CACHE_DIR/$blob" ]; then
		touch "$CACHE_DIR/$blob"
	else
		curl -s -L -H "$auth" "$url/blobs/$blob" -o "$CACHE_DIR/$blob"
	fi
	tar -C "$dir/rootfs" -xf "$CACHE_DIR/$blob"
done

echo "  cleanup"
rm "$dir/manifest.json"
find "$CACHE_DIR" -type f -mtime +30 -exec rm -f {} +

echo "successfully pulled $lib/$img@$tag to $dir"
